#!/usr/bin/env python3
"""Fail if any document asserts a test count, pass rate, or readiness grade without provenance.

ADR-0002 makes certification a generated artifact. This guard stops hand-authored readiness
claims from creeping back into docs/: a file may use readiness vocabulary only if it carries a
provenance header naming the commit and CI run that produced its numbers.

ADRs, design documents, and runbooks are exempt -- they assert intent, not measurement.

Usage: python3 scripts/check-certification-integrity.py [root]
"""

import re
import sys
from pathlib import Path

# Directories whose contents assert intent rather than measurement.
EXEMPT_DIRS = {"adr", "runbooks"}

# Pre-existing debt, grandfathered so this guard can land as a ratchet rather than a rewrite.
# ADR-0002 anticipated only the two certification documents (both retired by that ADR); these
# turned up when the guard was first run and were never reviewed by it. Each entry is a document
# asserting a score or pass rate with no run behind it. Remove entries as they are corrected or
# regenerated -- never add one.
GRANDFATHERED = {
    "IMMEDIATE_ACTIONS_COMPLETE.md",
    "IMPLEMENTATION_STATUS.md",
    "IMPLEMENTATION_SUMMARY.md",
    "PENTEST_DELIVERABLES.md",
    "PHASE_3_IMPLEMENTATION_COMPLETE.md",
    "PHASE_4_COMPLETE.md",
    "SWARM_IMPLEMENTATION_SUMMARY.md",
    "security/PENETRATION_TEST_REPORT.md",
    "security/PENTEST_SUMMARY.md",
    "security/SECURITY_SCORECARD.md",
}

READINESS_VOCABULARY = [
    (re.compile(r"certified\s+production[- ]ready", re.IGNORECASE), "certified production-ready"),
    (re.compile(r"test\s+pass\s+rate", re.IGNORECASE), "test pass rate"),
    (re.compile(r"\bPLATINUM\b"), "PLATINUM"),
    (re.compile(r"\b\d+\s*/\s*100\b"), "a score out of 100"),
    (re.compile(r"\bcertification\s+level\b", re.IGNORECASE), "certification level"),
    (re.compile(r"\boverall\s+grade\b", re.IGNORECASE), "overall grade"),
]

# A provenance header is the generator's stamp: which commit, which CI run.
PROVENANCE_MARKERS = (re.compile(r"^\|\s*Commit\s*\|", re.M), re.compile(r"^\|\s*CI run ID\s*\|", re.M))


def has_provenance(text):
    return all(marker.search(text) for marker in PROVENANCE_MARKERS)


def is_exempt(path, root):
    relative = path.relative_to(root)
    if EXEMPT_DIRS.intersection(relative.parts):
        return True
    return relative.as_posix() in GRANDFATHERED


def scan(root):
    violations = []
    for path in sorted(root.rglob("*.md")):
        if is_exempt(path, root):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if has_provenance(text):
            continue
        for pattern, label in READINESS_VOCABULARY:
            for match in pattern.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                violations.append((path, line, label, match.group(0).strip()))
    return violations


def main(argv):
    root = Path(argv[1] if len(argv) > 1 else "docs").resolve()
    if not root.is_dir():
        print(f"{root} is not a directory", file=sys.stderr)
        return 2

    violations = scan(root)
    if not violations:
        print(f"No unprovenanced readiness claims under {root}.")
        return 0

    print(f"Unprovenanced readiness claims under {root}:\n", file=sys.stderr)
    for path, line, label, snippet in violations:
        print(f"  {path}:{line}: {label} -- {snippet!r}", file=sys.stderr)
    print(
        "\nDocuments asserting a test count, pass rate, or readiness grade must be generated by\n"
        "scripts/generate-test-certification.py and carry its provenance header.\n"
        "See docs/adr/ADR-0002-certification-document-integrity.md.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
